### ISSUE TITLE
fork/exec /var/runtime/bootstrap: no such file or directory

### ISSUE THREAD

**Issue by tonycesar** [leoqbc/php8-aws-lambda-runtime#1]
Hi, can you try to rebuild and test in local or deploy un lambda, give errors, please:

time="2021-05-16T06:50:52.231" level=info msg="exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)"
time="2021-05-16T06:50:57.795" level=info msg="extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory"
time="2021-05-16T06:50:57.795" level=warning msg="Cannot list external agents" error="open /opt/extensions: no such file or directory"
START RequestId: 9d92576c-c377-4097-843d-84e616765a8f Version: $LATEST
time="2021-05-16T06:50:57.795" level=warning msg="First fatal error stored in appctx: Runtime.InvalidEntrypoint"
time="2021-05-16T06:50:57.795" level=error msg="Init failed" InvokeID= error="fork/exec /var/runtime/bootstrap: no such file or directory"
time="2021-05-16T06:50:57.796" level=warning msg="Failed to send default error response: ErrInvalidInvokeID"
time="2021-05-16T06:50:57.796" level=error msg="INIT DONE failed: Runtime.InvalidEntrypoint"
time="2021-05-16T06:50:57.796" level=warning msg="Reset initiated: ReserveFail"
START RequestId: a14b31b4-e43f-45f4-baf6-aca6616c9353 Version: $LATEST
time="2021-05-16T06:51:08.306" level=warning msg="Cannot list external agents" error="open /opt/extensions: no such file or directory"
time="2021-05-16T06:51:08.307" level=warning msg="First fatal error stored in appctx: Runtime.InvalidEntrypoint"

When try with curl test, give me 502 in first test and pending in second test

**Comment by tonycesar** [comment]
Sorry my fault, my files was open with CRLF, only change by LF my files and fix

**Comment by leoqbc** [comment]
Anyways thanks for using it! @tonycesar and feel free to contrib, I have a TODO to optime this container, I'm going to create the dockerfile on top of alpine distro, it'll take less memory consumption.
